# Generated by Django 3.1.5 on 2021-01-30 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_user_field(apps, schema_editor):
    """Add available value in exists objects"""
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Product = apps.get_model('main', 'Product')
    User = apps.get_model('auth', 'User')
    for product in Product.objects.all():
        product.vendor = User.objects.first()
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_vendor'),
    ]

    operations = [
        migrations.RunPython(add_user_field),
    ]
