# Generated by Django 3.1.5 on 2021-02-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210216_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='_vendor',
            new_name='vendor',
        ),
    ]
