# Generated by Django 3.1.5 on 2021-03-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210228_2036'),
    ]

    sql = """
            CREATE OR REPLACE VIEW main_viewcounter AS
            SELECT
                row_number() OVER () as id,
                main_product.name AS product_name,
                auth_user.username AS username,
                view_counter
            FROM
                auth_user INNER JOIN main_product
                ON auth_user.id = main_product.vendor_id
                ORDER BY view_counter DESC, username;
          """

    operations = [
        migrations.RunSQL("DROP VIEW IF EXISTS main_viewcounter;"),
        migrations.RunSQL(sql),
    ]
