version: '3.3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn django_lab.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/django_lab/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A django_lab worker -l info
    volumes:
      - ./django_lab:/django_lab
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
      - web
  daphne:
    build:
      context: .
    command: daphne --root-path "/ws" -b 0.0.0.0 -p 9001 --proxy-headers django_lab.asgi:application
    volumes:
      - ./django_lab:/django_lab
    expose:
      - 9001
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - web
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/django_lab/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume: