version: '3.3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/django_lab/
    hostname: 0.0.0.0
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    hostname: db
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=5muyc8qa
      - POSTGRES_DB=django_db
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A django_lab worker -l info
    volumes:
      - ./django_lab:/django_lab
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web
volumes:
  postgres_data: